default: &default
  # adapter: sqlite3 コメントアウトする
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3 # 追加
  database: storage/development.sqlite3

test:
  <<: *default
  adapter: sqlite3 # 追加
  database: storage/test.sqlite3

production:
  <<: *default
  adapter: postgresql # 追加
  encoding: unicode # 追加
  url: <%= ENV["DATABASE_URL"] %> # 追加